# Notes:
# The following default paths are local paths on the author's cloud machine.
# They are recorded for experiment reproducibility and do not contain access credentials.
#
# DF-03-02 Baseline 50-Sample Manifest Script
#
# This script selects a fixed 50-episode evaluation subset from the test split created by
# scripts/create_libero_episode_split.py.
#
# Important design:
# - The original RLDS / TFDS dataset is NOT copied, moved, or modified.
# - The script selects episode_index values only, not concrete step/image records.
# - The later baseline runner should enter each selected episode and choose one fixed step.
# - The selected 50 episodes must come from the test split only.
# - One JSON file is used as the single source of truth for the baseline runner.
#
# Expected input:
# results/splits/df_03_02_libero_episode_split_seed42.json
#
# Expected outputs:
# results/splits/df_03_02_baseline_50_samples_seed42.json
# results/tables/df_03_02_baseline_50_samples_manifest.csv
# logs/df_03_02_baseline_50_samples_log.md

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


# The function reads command-line settings for the split file, sample count, seed, and output paths.
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a fixed 50-episode baseline manifest from the LIBERO test split."
    )

    # This JSON is generated by scripts/create_libero_episode_split.py.
    parser.add_argument(
        "--split-json",
        type=str,
        default="results/splits/df_03_02_libero_episode_split_seed42.json",
        help="Path to the fixed LIBERO episode split JSON file.",
    )

    # DF-03-02 uses 50 fixed evaluation episodes before the larger runs.
    parser.add_argument(
        "--num-samples",
        type=int,
        default=50,
        help="Number of fixed baseline episodes to select from the test split.",
    )

    # The seed makes the 50-episode selection reproducible.
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed used for deterministic 50-episode selection.",
    )

    # DF-03-02 baseline evaluation must use test episodes, not train or validation episodes.
    parser.add_argument(
        "--target-split",
        type=str,
        default="test",
        choices=["train", "val", "test"],
        help="Split used for sample selection. DF-03-02 baseline should use test.",
    )

    # This JSON stores the selected 50 episodes as the single source of truth for the runner.
    parser.add_argument(
        "--output-json",
        type=str,
        default="results/splits/df_03_02_baseline_50_samples_seed42.json",
        help="Path for the selected 50-episode JSON manifest.",
    )

    # This CSV stores a table version of the selected 50 episodes.
    parser.add_argument(
        "--output-csv",
        type=str,
        default="results/tables/df_03_02_baseline_50_samples_manifest.csv",
        help="Path for the selected 50-episode CSV manifest.",
    )

    # This Markdown file records how the 50 episodes were selected.
    parser.add_argument(
        "--output-log",
        type=str,
        default="logs/df_03_02_baseline_50_samples_log.md",
        help="Path for the selected 50-episode Markdown log.",
    )

    return parser.parse_args()


# The function loads a JSON file from disk.
def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


# The function writes a JSON file with stable formatting.
def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        json.dump(data, file, indent=2, ensure_ascii=False)


# The function creates a stable integer seed for each sub-dataset.
def make_stable_sub_dataset_seed(seed: int, sub_dataset_name: str) -> int:
    seed_text = f"{seed}:baseline_50:{sub_dataset_name}"

    # SHA256 avoids Python hash randomization and keeps the seed stable across machines.
    digest = hashlib.sha256(seed_text.encode("utf-8")).hexdigest()

    # The first 16 hex characters are enough for deterministic sampling.
    return int(digest[:16], 16)


# The function calculates how many episodes should be selected from each sub-dataset.
def allocate_samples_by_test_size(
    sub_datasets: List[Dict[str, Any]],
    target_split: str,
    num_samples: int,
) -> Dict[str, int]:
    split_key = f"{target_split}_episode_indices"

    available_counts: Dict[str, int] = {}

    # The available count is the number of episodes in the chosen split for each sub-dataset.
    for record in sub_datasets:
        sub_dataset = record["sub_dataset"]
        available_counts[sub_dataset] = len(record.get(split_key, []))

    total_available = sum(available_counts.values())

    if total_available <= 0:
        raise ValueError(f"No episodes are available in target split: {target_split}")

    if num_samples > total_available:
        raise ValueError(
            f"Requested {num_samples} samples, but only {total_available} episodes are available."
        )

    allocations: Dict[str, int] = {}
    remainders: List[Dict[str, Any]] = []

    # The first allocation uses floor proportional allocation.
    for sub_dataset, available_count in available_counts.items():
        exact_count = num_samples * available_count / total_available
        floor_count = int(exact_count)

        allocations[sub_dataset] = floor_count

        remainders.append(
            {
                "sub_dataset": sub_dataset,
                "remainder": exact_count - floor_count,
                "available_count": available_count,
            }
        )

    remaining = num_samples - sum(allocations.values())

    # Remaining samples are assigned to the largest fractional remainders.
    remainders.sort(
        key=lambda item: (item["remainder"], item["available_count"], item["sub_dataset"]),
        reverse=True,
    )

    for item in remainders:
        if remaining <= 0:
            break

        sub_dataset = item["sub_dataset"]

        if allocations[sub_dataset] < available_counts[sub_dataset]:
            allocations[sub_dataset] += 1
            remaining -= 1

    if sum(allocations.values()) != num_samples:
        raise RuntimeError("Sample allocation failed to match the requested total sample count.")

    return allocations


# The function selects fixed episode indices from one sub-dataset split.
def select_episode_indices(
    episode_indices: List[int],
    sample_count: int,
    seed: int,
    sub_dataset_name: str,
) -> List[int]:
    if sample_count > len(episode_indices):
        raise ValueError(
            f"Requested {sample_count} samples from {sub_dataset_name}, "
            f"but only {len(episode_indices)} episodes are available."
        )

    local_seed = make_stable_sub_dataset_seed(seed=seed, sub_dataset_name=sub_dataset_name)

    # The copied list is shuffled so the source split JSON is never modified.
    shuffled_indices = list(episode_indices)
    random.Random(local_seed).shuffle(shuffled_indices)

    return shuffled_indices[:sample_count]


# The function builds the fixed 50-episode manifest from the selected test episodes.
def build_sample_manifest(
    split_data: Dict[str, Any],
    num_samples: int,
    seed: int,
    target_split: str,
) -> Dict[str, Any]:
    if target_split != "test":
        raise ValueError("DF-03-02 baseline 50 episodes must be selected from the test split.")

    sub_datasets = split_data.get("sub_datasets", [])
    split_key = f"{target_split}_episode_indices"

    allocations = allocate_samples_by_test_size(
        sub_datasets=sub_datasets,
        target_split=target_split,
        num_samples=num_samples,
    )

    samples: List[Dict[str, Any]] = []

    # Samples are selected per sub-dataset so all task suites stay represented.
    for record in sub_datasets:
        sub_dataset = record["sub_dataset"]
        task_suite = record.get("task_suite", "unknown")
        version_dir = record["version_dir"]
        source_split = record["source_split"]

        selected_indices = select_episode_indices(
            episode_indices=record.get(split_key, []),
            sample_count=allocations[sub_dataset],
            seed=seed,
            sub_dataset_name=sub_dataset,
        )

        for episode_index in selected_indices:
            samples.append(
                {
                    "sample_id": "",
                    "dataset_name": split_data["dataset_name"],
                    "sub_dataset": sub_dataset,
                    "task_suite": task_suite,
                    "source_split": source_split,
                    "eval_split": target_split,
                    "episode_index": episode_index,
                    "version_dir": version_dir,
                    "selection_seed": seed,
                    "sample_role": "df_03_02_baseline_50",
                    "selection_level": "episode",
                    "fixed_step_selected": False,
                    "fixed_step_policy": (
                        "The later baseline runner should enter this episode and select one fixed step."
                    ),
                    "notes": (
                        "Selected from the fixed test split. "
                        "This manifest stores episode-level samples only."
                    ),
                }
            )

    # The final order is stable and easy to read.
    samples.sort(key=lambda row: (row["sub_dataset"], row["episode_index"]))

    for index, sample in enumerate(samples, start=1):
        sample["sample_id"] = f"df_03_02_baseline_{index:03d}"

    allocation_rows = []

    for record in sub_datasets:
        sub_dataset = record["sub_dataset"]
        allocation_rows.append(
            {
                "sub_dataset": sub_dataset,
                "task_suite": record.get("task_suite", "unknown"),
                "available_test_episodes": len(record.get(split_key, [])),
                "selected_samples": allocations[sub_dataset],
            }
        )

    return {
        "task_id": "DF-03-02",
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "dataset_name": split_data["dataset_name"],
        "dataset_root": split_data["dataset_root"],
        "source_split": split_data["source_split"],
        "eval_split": target_split,
        "random_seed": seed,
        "num_samples": num_samples,
        "sample_source_rule": (
            "The 50 baseline episodes are selected only from test_episode_indices "
            "in the fixed episode split JSON. These samples are used for DF-03-02 "
            "pipeline and field-recording validation only."
        ),
        "selection_level": "episode",
        "step_selection_status": "not_selected_in_this_script",
        "step_selection_rule_for_runner": (
            "The baseline runner should read each selected episode_index, enter the episode, "
            "choose one fixed step, and then use image plus language_instruction for OpenVLA inference."
        ),
        "allocation_rule": (
            "Samples are allocated approximately proportional to each sub-dataset test size. "
            "Remainders are assigned by largest fractional remainder."
        ),
        "physical_data_copy": False,
        "single_source_of_truth": True,
        "allocation": allocation_rows,
        "samples": samples,
    }


# The function writes the selected episode manifest as a CSV table.
def write_csv(path: Path, manifest: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "sample_id",
        "dataset_name",
        "sub_dataset",
        "task_suite",
        "source_split",
        "eval_split",
        "episode_index",
        "version_dir",
        "selection_seed",
        "sample_role",
        "selection_level",
        "fixed_step_selected",
        "fixed_step_policy",
        "notes",
    ]

    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(manifest["samples"])


# The function writes a Markdown log for the selected 50 baseline episodes.
def write_markdown_log(path: Path, manifest: Dict[str, Any], output_json: Path, output_csv: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []

    lines.append("# DF-03-02 Baseline 50-Sample Manifest Log\n\n")

    lines.append("## Notes\n\n")
    lines.append("The following paths are local paths on the author's cloud machine.\n")
    lines.append("They are recorded for experiment reproducibility and do not contain access credentials.\n\n")

    lines.append("## Purpose\n\n")
    lines.append(
        "This log records the fixed 50-episode evaluation subset for the DF-03-02 LIBERO baseline run.\n\n"
    )
    lines.append(
        "This task does not run OpenVLA inference and does not train any model.\n\n"
    )

    lines.append("## Important Scope\n\n")
    lines.append(
        "This manifest selects episode indices only. It does not select concrete step indices or image frames.\n\n"
    )
    lines.append(
        "The later baseline runner should read each selected episode, choose one fixed step, "
        "and then use `observation.image` plus `language_instruction` for OpenVLA baseline inference.\n\n"
    )

    lines.append("## Sample Selection Settings\n\n")
    lines.append(f"- Dataset name: `{manifest['dataset_name']}`\n")
    lines.append(f"- Dataset root: `{manifest['dataset_root']}`\n")
    lines.append(f"- Source split: `{manifest['source_split']}`\n")
    lines.append(f"- Evaluation split: `{manifest['eval_split']}`\n")
    lines.append(f"- Random seed: `{manifest['random_seed']}`\n")
    lines.append(f"- Number of samples: `{manifest['num_samples']}`\n")
    lines.append(f"- Selection level: `{manifest['selection_level']}`\n")
    lines.append(f"- Step selection status: `{manifest['step_selection_status']}`\n")
    lines.append(f"- Physical data copy: `{manifest['physical_data_copy']}`\n")
    lines.append(f"- Output JSON: `{output_json}`\n")
    lines.append(f"- Output CSV: `{output_csv}`\n\n")

    lines.append("## Allocation Summary\n\n")
    lines.append("| Sub-dataset | Task suite | Available test episodes | Selected samples |\n")
    lines.append("|---|---|---:|---:|\n")

    for row in manifest["allocation"]:
        lines.append(
            f"| {row['sub_dataset']} | {row['task_suite']} | "
            f"{row['available_test_episodes']} | {row['selected_samples']} |\n"
        )

    lines.append("\n## Selected Samples\n\n")
    lines.append("| Sample ID | Sub-dataset | Task suite | Eval split | Episode index |\n")
    lines.append("|---|---|---|---|---:|\n")

    for sample in manifest["samples"]:
        lines.append(
            f"| {sample['sample_id']} | {sample['sub_dataset']} | "
            f"{sample['task_suite']} | {sample['eval_split']} | {sample['episode_index']} |\n"
        )

    lines.append("\n## How This Manifest Will Be Used\n\n")
    lines.append(
        "The baseline runner should read this manifest and run OpenVLA inference on these fixed 50 episodes only.\n\n"
    )
    lines.append(
        "The 50 selected episodes are only used to validate the DF-03-02 baseline pipeline, "
        "field recording, fixed step selection, action parsing, latency logging, and VRAM logging.\n\n"
    )
    lines.append(
        "Formal method evaluation will use the full test split / full-step open-loop evaluation, "
        "not this 50-sample debug manifest.\n\n"
    )

    path.write_text("".join(lines), encoding="utf-8")


# The function runs the full 50-sample manifest creation flow.
def main() -> None:
    args = parse_args()

    split_json = Path(args.split_json)
    output_json = Path(args.output_json)
    output_csv = Path(args.output_csv)
    output_log = Path(args.output_log)

    print("=" * 80)
    print("DF-03-02 Baseline 50-Sample Manifest")
    print("=" * 80)
    print(f"Split JSON: {split_json}")
    print(f"Split JSON exists: {split_json.exists()}")
    print(f"Target split: {args.target_split}")
    print(f"Number of samples: {args.num_samples}")
    print(f"Random seed: {args.seed}")
    print()

    if not split_json.exists():
        raise FileNotFoundError(f"Split JSON was not found: {split_json}")

    split_data = load_json(split_json)

    manifest = build_sample_manifest(
        split_data=split_data,
        num_samples=args.num_samples,
        seed=args.seed,
        target_split=args.target_split,
    )

    write_json(path=output_json, data=manifest)
    write_csv(path=output_csv, manifest=manifest)
    write_markdown_log(
        path=output_log,
        manifest=manifest,
        output_json=output_json,
        output_csv=output_csv,
    )

    print("Allocation summary:")
    for row in manifest["allocation"]:
        print(
            f"  {row['sub_dataset']}: "
            f"available_test={row['available_test_episodes']}, "
            f"selected={row['selected_samples']}"
        )

    print()
    print(f"Total selected samples: {len(manifest['samples'])}")
    print("=" * 80)
    print("Baseline 50-sample manifest finished.")
    print(f"JSON saved to: {output_json}")
    print(f"CSV saved to: {output_csv}")
    print(f"Markdown log saved to: {output_log}")
    print("=" * 80)


if __name__ == "__main__":
    main()
